# Generated by Django 3.2.4 on 2021-06-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nominee_Id', models.CharField(max_length=100, null=True, unique=True)),
                ('Nominee_Name', models.CharField(max_length=100)),
                ('Nominee_Photo', models.ImageField(upload_to='media/nominee/')),
                ('Party', models.CharField(max_length=100)),
                ('Sign', models.ImageField(upload_to='media/nominee')),
            ],
        ),
        migrations.CreateModel(
            name='CreateElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_code', models.CharField(max_length=100)),
                ('Election_Name', models.CharField(max_length=100)),
                ('Election_Start_Date', models.DateTimeField()),
                ('Election_End_Date', models.DateTimeField()),
                ('Election_Result_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Iris_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iris_image', models.ImageField(upload_to='media/Images')),
            ],
        ),
        migrations.CreateModel(
            name='last_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('Voter_Image', models.ImageField(null=True, upload_to='media/')),
                ('Voter_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Date_of_Birth', models.DateField(max_length=20, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=120, null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.TextField(max_length=250)),
                ('Address_Proof', models.ImageField(null=True, upload_to='media/')),
                ('Iris_Image', models.ImageField(null=True, upload_to=None)),
                ('Poling_Status', models.BooleanField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Nominee_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_app.add_nominee')),
                ('Voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_app.voter')),
            ],
        ),
    ]
