# Generated by Django 3.2.4 on 2021-07-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0003_alter_prediction_predicted_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='voting_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('Nominee_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_app.add_nominee')),
            ],
        ),
    ]
